name: autodeploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing-Initiation
        run: echo "Testing workflow initiation!"
      - name: Copy env.example to .env in api
        run: cp api/.env.example api/.env
      - name: Assign value in .env
        run: |
          sed -i 's/GOOGLE_SITE_KEY=.*/GOOGLE_SITE_KEY=${{ secrets.GOOGLE_SITE_KEY }}/' api/.env

      - name: Display  api .env contents
        run: cat api/.env
