name: autodeploy
'on':
  - push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Testing-Initiaion
        run: echo "Testing work flow intiation!"
      - name: Display repository folders and files
        run: ls -R
      - name: Display .env contents
        run: cd api
      - name: Display .env contents
        run: ls