name: autodeploy
'on':
  - push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Testing-Initiaion
        run: echo "Testing work flow intiation!"
      - name: creating-common-env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_GOOGLE_SITE_KEY: ${{ secrets.GOOGLE_SITE_KEY }}
          file_name: api/.env
          fail_on_empty: fals
      - name: Display .env contents
        run: cat api/.env